machine:
  pre:
    - curl -sSL https://s3.amazonaws.com/circle-downloads/install-circleci-docker.sh | bash -s -- 1.10.0
  services:
    - docker
  java:
    version: oraclejdk8

dependencies:
  pre:
    - docker info
    - mvn dependency:resolve
    - mvn clean package
    - mvn integration-test
    - docker build --rm=false -t royjoydeep1/udemy-rsmortgage-config-service-docker .

test:
  post:
    - docker run -d -p 8080:8080 -t royjoydeep1/udemy-rsmortgage-config-service-docker;  sleep 10
    - curl --retry 10 --retry-delay 5 -v http://localhost:8080
